name: HTML Validate

on:
  push:
    paths:
      - '**.html'
  pull_request:
    paths:
      - '**.html'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HTMLHint
        uses: Cyb3r-Jak3/htmlhint-action@v1.2.3
        with:
          files: '**/*.html'
